language: java
dist: bionic

jdk:
- openjdk8
- openjdk11
- openjdk17

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

script:
  - mvn test verify -B
    
branches:
  except:
  - gh-pages
    
cache:
  directories:
  - "$HOME/.m2"
