language: java
dist: bionic

jdk:
- openjdk8
- oraclejdk8

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"
    
branches:
  except:
  - gh-pages
    
cache:
  directories:
  - "$HOME/.m2"
