/*
 * (C) Copyright IBM Corp. 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.ibm_key_protect_api.v2.model;

import java.util.Date;

import com.google.gson.annotations.SerializedName;
import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * Partial properties of a client certificate.
 */
public class KMIPClientPartialCertificate extends GenericModel {

  protected String name;
  protected String id;
  @SerializedName("created_at")
  protected Date createdAt;
  @SerializedName("created_by")
  protected String createdBy;

  protected KMIPClientPartialCertificate() { }

  /**
   * Gets the name.
   *
   * A human-readable name that uniquely identifies a certificate within the given adapter. If one is  not specified,
   * one will be autogenerated of the format `kmip_cert_&lt;random_string&gt;`. To protect your privacy do not use
   * personal data, such as your name or location, as a name for your client certificate. The name must be  alphanumeric
   * and cannot contain spaces or special characters other than `-` or `_`. The name cannot be a UUID.
   *
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * Gets the id.
   *
   * The v4 UUID that uniquely identifies this certificate resource.
   *
   * @return the id
   */
  public String getId() {
    return id;
  }

  /**
   * Gets the createdAt.
   *
   * The date this certificate resource was created on the KMIP Adapter. The date format follows RFC 3339.
   *
   * @return the createdAt
   */
  public Date getCreatedAt() {
    return createdAt;
  }

  /**
   * Gets the createdBy.
   *
   * The IAM id that created the certificate resource.
   *
   * @return the createdBy
   */
  public String getCreatedBy() {
    return createdBy;
  }
}

